import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Juwon Mobile Gym</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href=''>Juwon Mobile Gym</a>
        </h1>

        <p className={styles.description}>
          Join Live Classes
        </p>
      </main>

      <footer className={styles.footer}>
        <div>Copyright @Juwon Mobile Fit, 2023</div>
      </footer>
    </div>
  )
}
